export enum Role {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  RECEPTIONIST = 'RECEPTIONIST',
  PHARMACIST = 'PHARMACIST',
  LAB_TECH = 'LAB_TECH',
  ACCOUNTANT = 'ACCOUNTANT',
  PATIENT = 'PATIENT',
}
